// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbrkucffhmhqnxlihmuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicmt1Y2ZmaG1ocW54bGlobXVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzgzNjcsImV4cCI6MjA2NTI1NDM2N30.iuQNs9J1YGGgsJOfNqPBLpMTnRv1hmS2FKAT6LuqtT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);